import React, { useState, useEffect } from 'react';
import axios from 'axios';

export default function Api() {
  const [data, setData] = useState({ hits: [] });
  const [query, setQuery] = useState('food');

  useEffect(() => {
    const fetchData = async () => {
      const result = await axios(
        'https://hn.algolia.com/api/v1/search?query=food'
      );

      setData(result.data);
    };

    fetchData();
  }, []);

  return (
    <React.Fragment>
      <input
        type="text"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
      />
      <ul>
        {data.hits.map((item) => (
          <li key={item.objectID}>
            <a href={item.url}>{item.title}</a>
          </li>
        ))}
      </ul>
    </React.Fragment>
  );
}

// const [movies, setMovies] = useState([]);

// for (const key in movies) {
//   loadedMovies.push({
//     id: key,
//     title: movies[key].title,
//     openingText: movies[key].openingText,
//     releaseDate: movies[key].releaseDate,
//   });
// }
// useEffect(() => {
//   axios
//     .get(
//       `https://react-course-http-40bac-default-rtdb.firebaseio.com/movies.json`
//     )
//     .then((res) => {
//       const loadedMovies = [];
//       if (res) {
//         for (let key in res.data) {
//           loadedMovies.push({
//             ...res.data[key],
//             id: key, //ids generated by Firebase
//             title: res.data[key].title,
//             openingText: res.data[key].openingText,
//             releaseDate: res.data[key].releaseDate,
//           });
//         }
//       }
//       // setMovies(loadedMovies);
//       console.log(res.data);
//       setMovies(res.data);
//       // const ffff = Object.values(res.data);
//     })
//     .catch((error) => {
//       console.log(error);
//     });
// }, []);
// return (
//   <div className="card text-center m-3">
//     <h3 key={movies.id}>prueba {Object.values.title}</h3>
//   </div>
// );
